// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grayPane': string;
  'header': string;
  'tooltip': string;
  'view': string;
}
export const cssExports: CssExports;
export default cssExports;
