// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevronArrow': string;
  'dark': string;
  'dropdown': string;
  'dropdownWrapper': string;
  'itemsContainer': string;
  'label': string;
  'open': string;
  'placeholder': string;
  'transparent': string;
}
export const cssExports: CssExports;
export default cssExports;
