// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'closeButton': string;
  'container': string;
  'containerWrapper': string;
  'error': string;
  'footer': string;
  'header': string;
  'loadingOverlay': string;
  'title': string;
  'tooltip': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
