// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'calenadrSection': string;
  'calendar': string;
  'contactSection': string;
  'description': string;
  'descriptionSection': string;
  'details': string;
  'disabledEquipmentItem': string;
  'equipmentGrid': string;
  'equipmentSection': string;
  'gallery': string;
  'gallerySection': string;
  'header': string;
  'image': string;
  'location': string;
  'logo': string;
  'name': string;
  'navButtons': string;
  'navButtonsWrapper': string;
  'sectionName': string;
  'seeMoreButton': string;
  'separator': string;
  'sportFacilityDetails': string;
  'stars': string;
}
export const cssExports: CssExports;
export default cssExports;
