// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'contactItem': string;
  'contactSection': string;
  'details': string;
  'header': string;
  'location': string;
  'logo': string;
  'name': string;
  'navButtons': string;
  'navButtonsWrapper': string;
  'sectionName': string;
  'separator': string;
  'sportFacilityDetails': string;
  'stars': string;
}
export const cssExports: CssExports;
export default cssExports;
