// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundImage': string;
  'contact': string;
  'contactSM': string;
  'description': string;
  'detailsSeparator': string;
  'detailsTitle': string;
  'eventDetails': string;
  'gradientOverlay': string;
  'header': string;
  'participantCell': string;
  'participantsList': string;
  'participantsListWrapper': string;
  'separator': string;
  'signUp': string;
  'signUpCell': string;
  'userData': string;
  'userDetails': string;
  'userDetailsRow': string;
  'userImage': string;
}
export const cssExports: CssExports;
export default cssExports;
