// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundImage': string;
  'detailsSeparator': string;
  'detailsTitle': string;
  'eventDetails': string;
  'gradientOverlay': string;
  'header': string;
  'userData': string;
  'userDetails': string;
  'userDetailsRow': string;
  'userImage': string;
}
export const cssExports: CssExports;
export default cssExports;
