// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarContainer': string;
  'comment': string;
  'commentAvatar': string;
  'comments': string;
  'content': string;
  'contentContainer': string;
  'contentHeader': string;
  'createdAt': string;
  'tooltip': string;
  'username': string;
  'writeCommentRow': string;
}
export const cssExports: CssExports;
export default cssExports;
