// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputWrapper': string;
  'label': string;
  'light': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
