// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'address': string;
  'busyBar': string;
  'date': string;
  'detailsRow': string;
  'divider': string;
  'eventTile': string;
  'image': string;
  'innerBar': string;
  'locationName': string;
  'price': string;
}
export const cssExports: CssExports;
export default cssExports;
