// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'locationSection': string;
  'restSection': string;
}
export const cssExports: CssExports;
export default cssExports;
