// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'eventImage': string;
  'eventImageWrapper': string;
  'label': string;
  'locationSection': string;
  'restSection': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
