// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ratingLower': string;
  'ratingUpper': string;
  'starRating': string;
}
export const cssExports: CssExports;
export default cssExports;
