// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevronArrow': string;
  'itemsContainer': string;
  'label': string;
  'open': string;
  'selectBox': string;
  'selectBoxWrapper': string;
  'transparent': string;
}
export const cssExports: CssExports;
export default cssExports;
