// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'checked': string;
  'rowContent': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
