// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authButtons': string;
  'mainContainer': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
