// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fieldName': string;
  'fieldValue': string;
  'groupHeader': string;
  'header': string;
  'image': string;
  'leftColumn': string;
  'rightColumn': string;
  'title': string;
  'userDataWrapper': string;
  'userView': string;
}
export const cssExports: CssExports;
export default cssExports;
