// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'changeImageInput': string;
  'editMode': string;
  'fieldName': string;
  'fieldRow': string;
  'fieldValue': string;
  'headerButtons': string;
  'image': string;
  'leftColumn': string;
  'rightColumn': string;
  'userDataWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
