// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authButtons': string;
  'avatar': string;
  'tooltip': string;
  'userButton': string;
}
export const cssExports: CssExports;
export default cssExports;
