// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authButtons': string;
  'avatar': string;
  'eventsDropdown': string;
  'menuButton': string;
  'menuDropdown': string;
  'tooltip': string;
  'userButton': string;
  'userDropdown': string;
}
export const cssExports: CssExports;
export default cssExports;
