// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authButtons': string;
  'brandbar': string;
  'links': string;
  'logo': string;
  'topbar': string;
}
export const cssExports: CssExports;
export default cssExports;
