// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blackButton': string;
  'grayButton': string;
  'orangeButton': string;
}
export const cssExports: CssExports;
export default cssExports;
