// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blackButton': string;
  'button': string;
  'facebookButton': string;
  'googleButton': string;
  'grayButton': string;
  'icon': string;
  'orangeButton': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
