// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'scrollbar': string;
  'thumb': string;
}
export const cssExports: CssExports;
export default cssExports;
